name: CI

on:
  push:
    branches: [main, feat/*, fix/*]  # Runs on push to these branches
  pull_request:
    branches: [main]  # Runs on PRs to these branches

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Resolve SPM Dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Build Project
        run: |
          xcodebuild clean build \
            -scheme WallaMarvel \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme WallaMarvel \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

      - name: Run SwiftLint
        run: |
          if which swiftlint >/dev/null; then
            swiftlint --strict
          else
            echo "SwiftLint not installed, skipping..."
          fi
